stability.api.key=sk-dNjouwX8hA805OXTAEbUZy4Jm6hnZlT1ZU6O0e3wRiTsvPkd

spring.ai.openai.api-key=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

spring.ai.openai.base-url=https://api.groq.com/openai

spring.ai.openai.chat.options.model=llama-3.3-70b-versatile